### ISSUE TITLE
Missing data in ClusterScanReport .spec.reportJSON

### ISSUE THREAD

**Issue by paraglade** [rancher/security-scan#28]
The following fields in the ClusterScanReport located at `.spec.reportJSON.results[].checks[]` are missing data
```
audit_config
actual_value
expected_result
```
This data is needed to produce the self-assessment documentation.

**Comment by prachidamle** [comment]
This data is read from the Kube-bench reports itself - so it seems the KB report does not print out this data. We might need to check the KB cli to see if there is a flag to output it.

**Comment by paraglade** [comment]
confirmed required data is in the report json and I am able to generate the needed docs.
tested with:`rancher-cis-benchmark:1.0.300`
