### ISSUE TITLE
Audit field in ClusterScanReport .spec.reportJSON not showing interpolated variables

### ISSUE THREAD

**Issue by paraglade** [rancher/security-scan#29]
The interpolated values of variables in the the audit field are not being rendered in the ClusterScanReport `.spec.reportJSON` for example:
`"audit": "/bin/sh -c 'if test -e $apiserverconf; then stat -c %a $apiserverconf; fi'",`

Should be:
`"audit": "/bin/sh -c 'if test -e /etc/kubernetes/manifests/kube-apiserver.yaml; then stat -c permissions=%a /etc/kubernetes/manifests/kube-apiserver.yaml; fi'"`

in the `reportJSON`

**Comment by prachidamle** [comment]
@paraglade These variables will have different values depending on the cluster types (rke1, rke2, k3s) and is cluster setup dependent (with custom benchmarks it might be something different than what we know of )- how will we know which value to use to replace the $apiserverconf

**Comment by prachidamle** [comment]
@maggieliu maybe this should move to 2.5.4 since it is being fixed with https://github.com/rancher/security-scan/issues/28

**Comment by paraglade** [comment]
confirmed interpolated data is in the report json and I am able to generate the needed docs.
tested with:`rancher-cis-benchmark:1.0.300`
